### ISSUE TITLE
Type error: Argument 1 passed to jorenvanhocht\Tracert\Tracert::__construct() must be an instance of Illuminate\Database\DatabaseManager

### ISSUE THREAD

**Issue by matrunchyk** [jorenvh/Tracert#1]
I use L5.2 and Tracert 2.0

It gives me the error:

`Type error: Argument 1 passed to jorenvanhocht\Tracert\Tracert::__construct() must be an instance of Illuminate\Database\DatabaseManager, instance of Illuminate\Foundation\Application`

when I run `php artisan vendor:publish --tag="config"`

**Comment by jorenvh** [comment]
Hi,

Seemed like their was a capital issue in the path of my config file.
Can't reproduce the error you are giving me, so maybe this solves the problem? I tagged a new version v2.0.1

24e6b971c4bd4097f97a2bb7bb5e7d78f41410c7

Can you let me know if this solved your problem?

**Comment by jorenvh** [comment]
<img width="488" alt="screen shot 2016-06-02 at 20 57 11" src="https://cloud.githubusercontent.com/assets/8791625/15757206/c21e13e2-2904-11e6-8805-f4ff97cc60ab.png">
